version: '3.8'

services:
  opcua-client:
    build: .
    env_file: .env
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - opcua_network
    restart: always  # Esto asegura que el contenedor siempre se reinicie

networks:
  opcua_network: